### ISSUE TITLE
[Enhancement] New Embed, phixiv

### ISSUE THREAD

**Issue by BloodDragooner2** [kenhendricks00/FixEmbed#1]
Heya, nice bot! Was wondering if you could add phixiv to embed pixiv.net links, created by HazeltheWitch, now [maintained by thelaao](https://github.com/thelaao/phixiv)? Appreciate it!!

**Comment by kenhendricks00** [comment]
Hello BloodDragooner2,
Thank you for the amazing suggestion and helping FixEmbed grow. I just added Pixiv support in the most recent update: https://github.com/kenhendricks00/FixEmbed/releases/tag/v1.1.1
Thanks,
Ken

**Comment by BloodDragooner2** [comment]
Cheers! Appreciate it :D
