### ISSUE TITLE
Mobile Links Dont WQork

### ISSUE THREAD

**Issue by ItsPrimeTimeX** [kenhendricks00/FixEmbed#2]
Mobile links not working. tiktok mobile links start in "vm" so its like "vm.tiktok.com/XXXXX" so ive noticed its not auto converting the mobile links.

**Comment by kenhendricks00** [comment]
Hello ItsPrimeTimeX,
Thank you for letting me know FixEmbed can't convert certain mobile links. Can you send me a random mobile TikTok link for testing purposes?
Thanks,
Ken

**Comment by ItsPrimeTimeX** [comment]
Sure, here’s one
https://vm.tiktok.com/ZMrayWrWp/

**Comment by kenhendricks00** [comment]
Thanks again, I just added TikTok mobile link support in the most recent update: https://github.com/kenhendricks00/FixEmbed/releases/tag/v1.1.2

**Comment by Sgaytor** [comment]
Doesn't seem to work for vt.tiktok.com either

e.g.

**Comment by Sgaytor** [comment]
Doesn't seem to work for vt.tiktok.com either

e.g. https://vt.tiktok.com/ZSYERLScr/

Debug:
![3a9b5465-1d91-4b7d-b452-9078c169079a](https://github.com/user-attachments/assets/918d7a50-5d6f-4b01-9f00-6c23202874e8)
