### ISSUE TITLE
[Enhancement] Remove embed rather than deleting message.

### ISSUE THREAD

**Issue by PortalRex** [kenhendricks00/FixEmbed#3]
Some people will put other text in a message with a link so rather than deleting the entire message with a link having an option that allows for the bot to just remove the embed would be nice. Thank you!

**Comment by kenhendricks00** [comment]
Hello PortalRex,
Sorry for the late reply, things have been busy. This is an amazing suggestion and one that has been requested often, I will aim to implement to adding this as an option in the settings in the next update.
Thanks,
Ken

**Comment by kenhendricks00** [comment]
The ability to toggle whether messages are deleted or embeds are just removed was added in the current update, thanks for the suggestion! :)
