### ISSUE TITLE
[Feature request] Filter posts out using RegEx or other parameters

### ISSUE THREAD

**Issue by DerekTurtleRoe** [kenhendricks00/FixEmbed#4]
Hello! I am really enjoying FixEmbed! 😄 

I was wanting a way to filter out posts by having a certain emoji or word within them, it would be nice if that was configurable.

As an example, you could make it so a post with a certain emoji or certain words wouldn't be automatically switched.

**Comment by kenhendricks00** [comment]
Hi DerekTurtleRoe,

Thanks for the kind words!

That sounds like a great idea, how about enclosing the link in <> or [] to avoid link conversion?

If you have a better way, I'd love to hear it.

Thanks,

Ken

**Comment by DerekTurtleRoe** [comment]
> Hi DerekTurtleRoe,
> 
> Thanks for the kind words!
> 
> That sounds like a great idea, how about enclosing the link in <> or [] to avoid link conversion?
> 
> If you have a better way, I'd love to hear it.
> 
> Thanks,
> 
> Ken

It still converts links when I do that, but I thought that was intentional in case another user tried to hide a link or something.

**Comment by kenhendricks00** [comment]
Sorry for the misunderstanding, I was asking if <> would be something you'd like to use. I just updated the bot to exclude links that are encased in <>, so they are not converted though. Thank you for the suggestion!
